### PR TITLE
fix seats io

### PR DESCRIPTION
**Pull request by ammarkdn**
Fix seats.io crashing on newer android versions

### CODE REVIEW

**Comment by ammarkdn** [comment]
Fix seats.io crashing on newer android versions

**Review by mroloux — COMMENTED** [review]
Hi, thanks for this PR.

Could you give some more context? Why exactly does the webview crash without the `androidLayerType` property?

**Comment by ammarkdn** [comment]
So the default value for WebView is *LAYER_TYPE_HARDWARE* which uses layers
that take up GPU memory, therefore whenever you render WebView it will take
time to load the inner page right? So whenever the page is not being loaded
(cuz it may take sometime)  it will crash app.

**Comment by mroloux** [comment]
Not sure I'm following 🤔 Do you have a code sample that makes the app crash? Trying to understand the issue here 😉

**Comment by ammarkdn** [comment]
Whenever I tried to run Seats.io on Android, it crashed immediately since
the page is not being loaded yet. I’ll share a video with you shortly.
Thank you

**Comment by ammarkdn** [comment]
For some reason, the emulator is not getting recorded. So can you test it on your side with the latest Android version? Thank you.

**Comment by mroloux** [comment]
I tested with an emulator on Android API 33. That worked fine.

Do you get any errors?

**Comment by ammarkdn** [comment]
Yes. It crashed the app. Even when using the regular WebView component

**Comment by mroloux** [comment]
Ok, but did you get any errors in particular?

**Comment by ammarkdn** [comment]
No unfortunately :(

**Comment by mroloux** [comment]
Hm, very weird. We'll need something that helps in reproducing this (a video, stack trace...).

**Comment by mroloux** [comment]
Closing this for now, until we receive more info.

**Pull request closed without merging**
