### PR TITLE
added new props (style, containerStyle)

### PR DESCRIPTION
**Pull request by Buwaneka-Sumanasekara**
added new props (style,containerStyle) to customize styles of webview

### CODE REVIEW

**Comment by bverbeken** [comment]
Thanks for sending a PR. 
Can you elaborate please, what problem does this solve?

**Comment by Buwaneka-Sumanasekara** [comment]
@bverbeken  I have added 2 props to `SeatsioSeatingChart` component called `style` and `containerStyle`. Which allow to customize style and containerStyle of WebView.

**Comment by bverbeken** [comment]
@Buwaneka-Sumanasekara Thanks, I can see that. 

We may add a `style` parameter in the future to allow styling the SeatingChart component, but not in the way you propose in this PR. 
The reason is that the react-native-webview [docs](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#style) for `style` and `containerStyle` mention that there are "default styles" without specifying what these default styles are. And we prefer our package not to be dependent on (undocumented!) defaults set by a dependency. 

So we'd rather add a wrapper element inside the Webview, and style that via a new `style` prop. Which would come down to moving this View element inside the webview html: https://github.com/seatsio/seatsio-react-native/blob/master/example/examples/SimpleSeatingChart.js#L12

Does that make sense?

**Comment by buwaneka-zerobeta** [comment]
Cool. yup no problem

**Pull request closed without merging**
